ALTER TABLE jobs ADD COLUMN stages_json   TEXT    NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN prev_job_id   TEXT    NOT NULL DEFAULT '';
