ALTER TABLE jobs ADD COLUMN spill_count  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN spill_bytes  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN merge_rounds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN merge_bytes  INTEGER NOT NULL DEFAULT 0;
