package templates

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
)

// tailwindCSS is the compiled Tailwind output, generated by `make css`
// from styles/input.css against the project's templates. Build is
// AOT — there is no JIT-in-browser dependency at runtime.
//
//go:embed styles/tailwind.css
var tailwindCSS []byte

// TailwindCSS returns the embedded compiled stylesheet.
func TailwindCSS() []byte { return tailwindCSS }

// TailwindCSSETag returns a weak ETag derived from the compiled CSS
// content, so the browser can revalidate cheaply across deploys.
var TailwindCSSETag = func() string {
	h := sha256.Sum256(tailwindCSS)
	return `W/"` + hex.EncodeToString(h[:8]) + `"`
}()
