package templates

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
)

// tailwindCSS is the compiled Tailwind output, generated by `make css`
// from styles/input.css against the project's templates. Build is
// AOT — there is no JIT-in-browser dependency at runtime.
//
//go:embed styles/tailwind.css
var tailwindCSS []byte

//go:embed scripts/help.js
var helpJS []byte

// TailwindCSS returns the embedded compiled stylesheet.
func TailwindCSS() []byte { return tailwindCSS }

// HelpJS returns the embedded help-page JS (TOC active link + filter).
func HelpJS() []byte { return helpJS }

// TailwindCSSETag returns a weak ETag derived from the compiled CSS
// content, so the browser can revalidate cheaply across deploys.
// SHA-256 over an embedded ~tens-of-KiB byte slice is in the
// few-microseconds range and runs on the GET /static/tailwind.css path
// only, so computing per call (rather than caching in a package var)
// is the right trade.
func TailwindCSSETag() string {
	return weakETag(tailwindCSS)
}

// HelpJSETag returns a weak ETag for HelpJS, mirroring TailwindCSSETag.
func HelpJSETag() string {
	return weakETag(helpJS)
}

func weakETag(content []byte) string {
	h := sha256.Sum256(content)

	return `W/"` + hex.EncodeToString(h[:8]) + `"`
}
